image: node:10.9.0 # Should match .nvmrc content

stages:
  - tests
  - build
  - deploy
  - publish

cache:
  paths:
    - node_modules/

before_script:
  - node --version
  - npm --version
  - ls -alh

# Tests stage

npm_test:
  tags: [shared-ci-docker]
  stage: tests
  script:
    - npm ci
    - npm run lint
    - npm run coverage
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/


npm_run_build:
  tags: [shared-ci-docker]
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    expire_in: 2 days
    name: "build-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}"
    paths:
      - dist

# Deploy story book

build_story_book:
  tags: [shared-ci-docker]
  stage: build
  script:
    - npm ci
    - npm run build-storybook
  artifacts:
    expire_in: 3 days
    paths:
      - storybook-static/

deploy_story_book:
  tags: [shared-ci-docker]
  stage: deploy
  dependencies:
    - build_story_book
  only:
    - v2
  script:
    - npx --package netlify-cli netlify deploy --site=$NETLIFY_SITE_ID --auth=$NETLIFY_ACCESS_TOKEN  --dir=./storybook-static --prod

# Publish on npm

npm_run_deploy:
  tags: [shared-ci-docker]
  stage: publish
  only:
    - tags
  dependencies:
    - npm_run_build
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}">~/.npmrc
    - scripts/publish.sh
